# Generated by Django 4.2.18 on 2025-01-29 02:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
