# Generated by Django 4.2.18 on 2025-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
