# Generated by Django 4.2.18 on 2025-01-29 09:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0002_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=tinymce.models.HTMLField(),
        ),
    ]
