# Generated by Django 4.2.18 on 2025-01-29 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capp", "0003_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
